project_id = "fizcmvavzgoaznzindwl"

[functions.fetch-news]
verify_jwt = false

[functions.get-youtube-duration]
verify_jwt = false

[functions.belinha-chat]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.baserow-content]
verify_jwt = false

[functions.baserow-list-tables]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.pdf-proxy]
verify_jwt = false

[functions.art-proxy]
verify_jwt = false
